[package]
authors = ["Tsiry Sandratraina <tsiry.sndr@aol.com>"]
description = "The client library for the music player"
edition = "2021"
keywords = ["tokio", "music", "cli", "daemon", "streaming"]
license = "MIT"
name = "music-player-client"
repository = "https://github.com/tsirysndr/music-player"
version = "0.1.5"

[dev-dependencies]
envtestkit = "1.1.2"
extism = "1.5.0"
music-player-host-fn = {path = "../host_fn", version = "0.1.0"}
tonic-web = "0.4.0"
ureq = "2.10.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.music-player-server]
path = "../server"
version = "0.2.0"

[dependencies.music-player-settings]
path = "../settings"
version = "0.1.3"

[dependencies.music-player-types]
path = "../types"
version = "0.1.3"

[dev-dependencies.music-player-playback]
path = "../playback"
version = "0.1.10"

[dev-dependencies.music-player-storage]
path = "../storage"
version = "0.1.4"

[dev-dependencies.music-player-tracklist]
path = "../tracklist"
version = "0.1.7"

[dependencies]
anyhow = "1.0.67"
futures-util = "0.3.24"
tokio = {version = "1.21.2", features = ["full"]}
tokio-tungstenite = "0.17.2"
tonic = "0.8.1"
url = "2.3.1"
