load("//cargo:crates.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "music-player",
    srcs = [
      "src/event/events.rs",
      "src/event/key.rs",
      "src/event/mod.rs",
      "src/handlers/album_tracks.rs",
      "src/handlers/library.rs",
      "src/handlers/albums.rs",
      "src/handlers/mod.rs",
      "src/handlers/artist_tracks.rs",
      "src/handlers/play_queue.rs",
      "src/handlers/artists.rs",
      "src/handlers/playbar.rs",
      "src/handlers/common_key_events.rs",
      "src/handlers/playlist.rs",
      "src/handlers/empty.rs",
      "src/handlers/tracks.rs",
      "src/handlers/input.rs",
      "src/ui/mod.rs",
      "src/ui/util.rs",
      "src/app.rs",
      "src/main.rs",
      "src/scan.rs",
      "src/args.rs",
      "src/network.rs",
      "src/user_config.rs",
    ],
    deps = [
      "//addons:addons_lib",
      "//client:client_lib",
      "//discovery:discovery_lib",
      "//entity:entity_lib",
      "//graphql:graphql_lib",
      "//migration:migration_lib",
      "//playback:playback_lib",
      "//scanner:scanner_lib",
      "//server:server_lib",
      "//settings:settings_lib",
      "//storage:storage_lib",
      "//tracklist:tracklist_lib",
      "//types:types_lib",
      "//webui:webui_lib",
    ] + all_crate_deps(),
)