[package]
authors = ["Jacob Stern <jacob.stern@outlook.com>"]
default-run = "app"
description = "A Tauri App"
edition = "2021"
license = ""
name = "app"
repository = ""
rust-version = "1.77.2"
version = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "2", features = []}

[dependencies.music-player-renderer]
path = "../../../renderer"
version = "0.2.1"

[dependencies.music-player-provider]
path = "../../../provider"
version = "0.2.1"

[dependencies.music-player-server]
path = "../../../server"
version = "0.2.1"

[dependencies.music-player-migration]
path = "../../../migration"
version = "0.2.1"

[dependencies.music-player-webui]
path = "../../../webui"
version = "0.2.1"

[dependencies.music-player-discovery]
path = "../../../discovery"
version = "0.2.1"

[dependencies.music-player-graphql]
path = "../../../graphql"
version = "0.2.1"

[dependencies.music-player-settings]
path = "../../../settings"
version = "0.2.1"

[dependencies.music-player-storage]
path = "../../../storage"
version = "0.2.1"

[dependencies.music-player-playback]
path = "../../../playback"
version = "0.2.1"

[dependencies.music-player-tracklist]
path = "../../../tracklist"
version = "0.2.1"

[dependencies.music-player-types]
path = "../../../types"
version = "0.2.1"

[dependencies]
actix-web = "4.15.0"
async-graphql = "7.2.1"
async-graphql-actix-web = "7.2.1"
futures = "0.3.24"
futures-channel = "0.3.24"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tauri = {version = "2", features = ["protocol-asset"]}
tokio = {version = "1.21.2", features = ["full"]}
tungstenite = "0.17.3"
sea-orm = {version = "0.9.2", features = ["runtime-tokio-rustls", "sqlx-sqlite"]}
tracing = "0.1"
uuid = "1.1.2"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
