syntax = "proto3";

package music.v1alpha1;

message GetMuteRequest {}

message GetMuteResponse {
  bool mute = 1;
}

message SetMuteRequest {
  bool mute = 1;
}

message SetMuteResponse {}

message GetVolumeRequest {}

message GetVolumeResponse {
  uint32 volume = 1;
}

message SetVolumeRequest {
  uint32 volume = 1;
}

message SetVolumeResponse {}

service MixerService {
  rpc GetMute(GetMuteRequest) returns (GetMuteResponse) {}
  rpc SetMute(SetMuteRequest) returns (SetMuteResponse) {}
  rpc GetVolume(GetVolumeRequest) returns (GetVolumeResponse) {}
  rpc SetVolume(SetVolumeRequest) returns (SetVolumeResponse) {}
}