[package]
authors = ["Tsiry Sandratraina <tsiry.sndr@aol.com>"]
categories = ["command-line-utilities"]
description = "The GraphQL server API for the music player"
edition = "2021"
keywords = ["tokio", "music", "cli", "daemon", "streaming"]
license = "MIT"
name = "music-player-graphql"
repository = "https://github.com/tsirysndr/music-player"
version = "0.1.10"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.music-player-playback]
path = "../playback"
version = "0.1.10"

[dependencies.music-player-scanner]
path = "../scanner"
version = "0.1.8"

[dependencies.music-player-settings]
path = "../settings"
version = "0.1.4"

[dependencies.music-player-storage]
path = "../storage"
version = "0.1.6"

[dependencies.music-player-entity]
path = "../entity"
version = "0.1.7"

[dependencies.music-player-tracklist]
path = "../tracklist"
version = "0.1.7"

[dependencies.music-player-types]
path = "../types"
version = "0.1.3"

[dependencies.music-player-discovery]
path = "../discovery"
version = "0.1.2"

[dependencies.music-player-addons]
path = "../addons"
version = "0.1.5"

[dependencies.music-player-host-fn]
path = "../host_fn"
version = "0.1.0"

[dev-dependencies.music-player-migration]
path = "../migration"
version = "0.1.6"

[dev-dependencies]
ctor = "0.1.26"

[dependencies]
anyhow = "1.0.67"
async-graphql = "4.0.15"
async-graphql-tide = "4.0.15"
chrono = "0.4.23"
cuid = "1.2.0"
extism = "1.5.0"
futures-channel = "0.3.25"
futures-util = "0.3.25"
md5 = "0.7.0"
mdns-sd = "0.5.9"
music-player-pdk = {version = "0.1.0", path = "../pdk"}
once_cell = "1.16.0"
rand = "0.8.5"
sea-orm = {version = "0.9.3", features = ["runtime-tokio-rustls", "sqlx-sqlite"]}
serde = {version = "1.0.148", features = ["serde_derive"]}
slab = "0.4.7"
tide = "0.16.0"
tokio = {version = "1.21.0", features = ["full"]}
upnp-client = "0.1.9"
ureq = "2.10.1"
url = "2.3.1"
