[package]
authors = ["Tsiry Sandratraina <tsiry.sndr@rocksky.app>"]
description = "The web ui of music player"
edition = "2021"
keywords = ["tokio", "music", "cli", "daemon", "streaming"]
license = "MIT"
name = "music-player-webui"
repository = "https://github.com/tsirysndr/music-player"
version = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.music-player-graphql]
path = "../graphql"
version = "0.2.1"

[dependencies.music-player-settings]
path = "../settings"
version = "0.2.1"

[dependencies.music-player-storage]
path = "../storage"
version = "0.2.1"

[dependencies.music-player-playback]
path = "../playback"
version = "0.2.1"

[dependencies.music-player-tracklist]
path = "../tracklist"
version = "0.2.1"

[dependencies.music-player-entity]
path = "../entity"
version = "0.2.1"

[dev-dependencies.music-player-scanner]
path = "../scanner"
version = "0.2.1"

[dependencies.music-player-discovery]
path = "../discovery"
version = "0.2.1"

[dependencies.music-player-types]
path = "../types"
version = "0.2.1"

[dependencies.music-player-provider]
path = "../provider"
version = "0.2.1"

[dependencies.music-player-addons]
path = "../addons"
version = "0.2.1"

[dev-dependencies]
futures-util = "0.3.25"
serde_json = "1.0.89"

sea-orm = {version = "0.9.3", features = ["runtime-tokio-rustls", "sqlx-sqlite"]}
surf = {version = "2.3.2", features = ["h1-client-rustls"], default-features = false}

[dependencies]
actix-cors = "0.7.2"
actix-files = "0.7.0"
actix-web = "4.15.0"
async-graphql = "7.2.1"
async-graphql-actix-web = "7.2.1"
dirs = "4.0.0"
futures = "0.3.28"
futures-util = "0.3.25"
mime = "0.3.16"
mime_guess = "2.0.4"
owo-colors = "3.5.0"
rust-embed = {version = "8.12.0", features = ["debug-embed", "actix"]}
sea-orm = {version = "0.9.3", features = ["runtime-tokio-rustls", "sqlx-sqlite"]}
serde = {version = "1.0.145", features = ["serde_derive"]}
serde_derive = "1.0.145"
tokio = {version = "1.21.2", features = ["full"]}

[dev-dependencies.music-player-migration]
path = "../migration"
version = "0.2.1"
