// THIS FILE WAS GENERATED BY `xtp-rust-bindgen`. DO NOT EDIT.

#![allow(non_snake_case)]
#![allow(unused_macros)]
use extism_pdk::*;

#[allow(unused)]
fn panic_if_key_missing() -> ! {
    panic!("missing key");
}

pub(crate) mod internal {
    pub(crate) fn return_error(e: extism_pdk::Error) -> i32 {
        let err = format!("{:?}", e);
        let mem = extism_pdk::Memory::from_bytes(&err).unwrap();
        unsafe {
            extism_pdk::extism::error_set(mem.offset());
        }
        -1
    }
}

#[allow(unused)]
macro_rules! try_input {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(x) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

#[allow(unused)]
macro_rules! try_input_json {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(extism_pdk::Json(x)) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

use base64_serde::base64_serde_type;

base64_serde_type!(Base64Standard, base64::engine::general_purpose::STANDARD);

mod exports {
    use super::*;

    #[no_mangle]
    pub extern "C" fn commands() -> i32 {
        let ret = crate::commands().and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn evaluate() -> i32 {
        let ret = crate::evaluate(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn get_metadata() -> i32 {
        let ret = crate::get_metadata(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn get_stream_url() -> i32 {
        let ret = crate::get_stream_url(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn list_albums() -> i32 {
        let ret = crate::list_albums(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn list_artists() -> i32 {
        let ret = crate::list_artists(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn list_playlists() -> i32 {
        let ret = crate::list_playlists(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn list_tracks() -> i32 {
        let ret = crate::list_tracks(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn on_playlist_created() -> i32 {
        let ret = crate::on_playlist_created(try_input_json!()).and_then(extism_pdk::output);

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn on_scan_completed() -> i32 {
        let ret = crate::on_scan_completed(try_input_json!()).and_then(extism_pdk::output);

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn on_track_liked() -> i32 {
        let ret = crate::on_track_liked(try_input_json!()).and_then(extism_pdk::output);

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn on_track_played() -> i32 {
        let ret = crate::on_track_played(try_input_json!()).and_then(extism_pdk::output);

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn on_track_skipped() -> i32 {
        let ret = crate::on_track_skipped(try_input_json!()).and_then(extism_pdk::output);

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn predicates() -> i32 {
        let ret = crate::predicates().and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn run_command() -> i32 {
        let ret = crate::run_command(try_input_json!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }

    #[no_mangle]
    pub extern "C" fn source_info() -> i32 {
        let ret = crate::source_info().and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }
}

pub mod types {
    use super::*;

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct BrowseRequest {
        /// Maximum items to return. 0 or absent means the host's default.
        #[serde(rename = "limit")]
        pub limit: i32,

        #[serde(rename = "offset")]
        pub offset: i32,

        /// List the children of this album, artist or playlist. Empty lists
        /// everything at the top level.
        #[serde(rename = "parentId")]
        pub parent_id: String,

        /// Free-text search. Empty browses rather than searches.
        #[serde(rename = "query")]
        pub query: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct CommandRequest {
        /// Free-form JSON arguments from the caller.
        #[serde(rename = "args")]
        pub args: String,

        #[serde(rename = "name")]
        pub name: String,

        #[serde(rename = "track")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub track: Option<types::Track>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct CommandResponse {
        /// Anything structured the caller wants back, as JSON.
        #[serde(rename = "data")]
        pub data: String,

        /// A line to show the user.
        #[serde(rename = "message")]
        pub message: String,

        #[serde(rename = "ok")]
        pub ok: bool,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct CommandSpec {
        #[serde(rename = "description")]
        pub description: String,

        /// Identifier passed back to `run_command`.
        #[serde(rename = "name")]
        pub name: String,

        /// Whether the command wants the current track passed in.
        #[serde(rename = "needsTrack")]
        pub needs_track: bool,

        /// What the UI shows.
        #[serde(rename = "title")]
        pub title: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct LibraryAlbum {
        #[serde(rename = "artist")]
        pub artist: String,

        /// Cover file name, resolvable through the player's cover route.
        #[serde(rename = "cover")]
        pub cover: String,

        #[serde(rename = "id")]
        pub id: String,

        #[serde(rename = "title")]
        pub title: String,

        #[serde(rename = "year")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub year: Option<i32>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct LibraryArtist {
        #[serde(rename = "id")]
        pub id: String,

        #[serde(rename = "image")]
        pub image: String,

        #[serde(rename = "name")]
        pub name: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct LibraryPlaylist {
        #[serde(rename = "description")]
        pub description: String,

        #[serde(rename = "id")]
        pub id: String,

        #[serde(rename = "isSmart")]
        pub is_smart: bool,

        #[serde(rename = "name")]
        pub name: String,

        #[serde(rename = "trackCount")]
        pub track_count: i32,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct LibraryQuery {
        /// RSQL over the track fields, e.g. `genre==rock;year>2000`.
        #[serde(rename = "filter")]
        pub filter: String,

        /// Maximum rows to return. 0 or absent is unlimited.
        #[serde(rename = "limit")]
        pub limit: i32,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct LikeEvent {
        /// True when liked, false when the like was removed.
        #[serde(rename = "liked")]
        pub liked: bool,

        #[serde(rename = "track")]
        pub track: types::Track,

        /// Always `track_liked`.
        #[serde(rename = "type")]
        pub r#type: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct MetadataRequest {
        #[serde(rename = "track")]
        pub track: types::Track,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct MetadataResponse {
        #[serde(rename = "artworkUrl")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub artwork_url: Option<String>,

        /// Artist biography.
        #[serde(rename = "bio")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub bio: Option<String>,

        /// Genre tags this provider would apply.
        #[serde(rename = "genres")]
        pub genres: Vec<String>,

        /// Plain text or LRC.
        #[serde(rename = "lyrics")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub lyrics: Option<String>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct PlayEvent {
        /// How many times this track has now been played.
        #[serde(rename = "playCount")]
        pub play_count: i32,

        /// Unix seconds when the play started.
        #[serde(rename = "playedAt")]
        pub played_at: i64,

        #[serde(rename = "track")]
        pub track: types::Track,

        /// Always `track_played`.
        #[serde(rename = "type")]
        pub r#type: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct PlaylistEvent {
        #[serde(rename = "id")]
        pub id: String,

        #[serde(rename = "isSmart")]
        pub is_smart: bool,

        #[serde(rename = "name")]
        pub name: String,

        /// Always `playlist_created`.
        #[serde(rename = "type")]
        pub r#type: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct PredicateRequest {
        #[serde(rename = "name")]
        pub name: String,

        /// The comparison written in the filter: ==, !=, >, >=, <, <=.
        #[serde(rename = "op")]
        pub op: String,

        #[serde(rename = "track")]
        pub track: types::Track,

        #[serde(rename = "value")]
        pub value: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct PredicateResponse {
        #[serde(rename = "matches")]
        pub matches: bool,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct PredicateSpec {
        #[serde(rename = "description")]
        pub description: String,

        /// The name used in a filter, e.g. `mood` for `ext:mood==chill`.
        #[serde(rename = "name")]
        pub name: String,

        /// Example values, shown in a picker.
        #[serde(rename = "values")]
        pub values: Vec<String>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct SavedRadio {
        #[serde(rename = "bitrate")]
        pub bitrate: i32,

        #[serde(rename = "country")]
        pub country: String,

        #[serde(rename = "genre")]
        pub genre: String,

        #[serde(rename = "id")]
        pub id: String,

        #[serde(rename = "logo")]
        pub logo: String,

        #[serde(rename = "name")]
        pub name: String,

        #[serde(rename = "source")]
        pub source: String,

        #[serde(rename = "streamUrl")]
        pub stream_url: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct ScanEvent {
        #[serde(rename = "totalTracks")]
        pub total_tracks: i32,

        #[serde(rename = "tracksAdded")]
        pub tracks_added: i32,

        /// Always `scan_completed`.
        #[serde(rename = "type")]
        pub r#type: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct SkipEvent {
        #[serde(rename = "skippedAt")]
        pub skipped_at: i64,

        #[serde(rename = "track")]
        pub track: types::Track,

        /// Always `track_skipped`.
        #[serde(rename = "type")]
        pub r#type: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct SourceAlbum {
        #[serde(rename = "artist")]
        pub artist: String,

        #[serde(rename = "coverUrl")]
        pub cover_url: String,

        /// The source's own id, passed back as `parentId`.
        #[serde(rename = "id")]
        pub id: String,

        #[serde(rename = "title")]
        pub title: String,

        #[serde(rename = "year")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub year: Option<i32>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct SourceArtist {
        #[serde(rename = "id")]
        pub id: String,

        #[serde(rename = "imageUrl")]
        pub image_url: String,

        #[serde(rename = "name")]
        pub name: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct SourceInfo {
        #[serde(rename = "description")]
        pub description: String,

        /// Shown in the source picker, e.g. "Bandcamp".
        #[serde(rename = "name")]
        pub name: String,

        /// Whether the source needs credentials. Declare the keys it reads
        /// under `permissions.config` in the manifest.
        #[serde(rename = "requiresAuth")]
        pub requires_auth: bool,

        /// Whether the `query` field of a browse request is honoured.
        #[serde(rename = "supportsSearch")]
        pub supports_search: bool,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct SourcePlaylist {
        #[serde(rename = "description")]
        pub description: String,

        #[serde(rename = "id")]
        pub id: String,

        #[serde(rename = "name")]
        pub name: String,

        #[serde(rename = "trackCount")]
        pub track_count: i32,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct StreamRequest {
        /// The source's own track id.
        #[serde(rename = "trackId")]
        pub track_id: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct StreamResponse {
        /// Extra request headers as a JSON object, for a source that needs an
        /// Authorization header. Empty when none are needed.
        #[serde(rename = "headers")]
        pub headers: String,

        #[serde(rename = "mimeType")]
        pub mime_type: String,

        /// A direct http(s) url the player can decode.
        #[serde(rename = "url")]
        pub url: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct Track {
        #[serde(rename = "album")]
        pub album: String,

        #[serde(rename = "albumArtist")]
        pub album_artist: String,

        #[serde(rename = "artist")]
        pub artist: String,

        /// Length in seconds.
        #[serde(rename = "duration")]
        pub duration: f32,

        #[serde(rename = "genre")]
        pub genre: String,

        /// Stable library id.
        #[serde(rename = "id")]
        pub id: String,

        #[serde(rename = "title")]
        pub title: String,

        #[serde(rename = "trackNumber")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub track_number: Option<i32>,

        /// File path or stream url.
        #[serde(rename = "uri")]
        pub uri: String,

        #[serde(rename = "year")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub year: Option<i32>,
    }
}

mod raw_imports {
    use super::*;
    #[host_fn]
    extern "ExtismHost" {

        pub(crate) fn get_config(input: String) -> String;

        pub(crate) fn get_playlist_tracks(input: String) -> Json<Vec<types::Track>>;

        pub(crate) fn get_saved_radios() -> Json<Vec<types::SavedRadio>>;

        pub(crate) fn log(input: String);

        pub(crate) fn query_albums(
            input: Json<types::LibraryQuery>,
        ) -> Json<Vec<types::LibraryAlbum>>;

        pub(crate) fn query_artists(
            input: Json<types::LibraryQuery>,
        ) -> Json<Vec<types::LibraryArtist>>;

        pub(crate) fn query_library(input: Json<types::LibraryQuery>) -> Json<Vec<types::Track>>;

        pub(crate) fn query_playlists(
            input: Json<types::LibraryQuery>,
        ) -> Json<Vec<types::LibraryPlaylist>>;

    }
}

/// get_config Read one of the config values declared in `plugin.json`. Returns an empty
/// string for a key that was not declared or has no value.
#[allow(unused)]
pub(crate) fn get_config(input: String) -> std::result::Result<String, extism_pdk::Error> {
    let res = unsafe { raw_imports::get_config(input)? };

    Ok(res)
}

/// get_playlist_tracks The tracks of one playlist, in order. Requires the `libraryRead`
/// permission.
#[allow(unused)]
pub(crate) fn get_playlist_tracks(
    input: String,
) -> std::result::Result<Vec<types::Track>, extism_pdk::Error> {
    let res = unsafe { raw_imports::get_playlist_tracks(input)? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// get_saved_radios The user's bookmarked radio stations. Requires the `libraryRead`
/// permission.
#[allow(unused)]
pub(crate) fn get_saved_radios() -> std::result::Result<Vec<types::SavedRadio>, extism_pdk::Error> {
    let res = unsafe { raw_imports::get_saved_radios()? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// log Write a line to the host's log, prefixed with the extension id.
#[allow(unused)]
pub(crate) fn log(input: String) -> std::result::Result<(), extism_pdk::Error> {
    let res = unsafe { raw_imports::log(input)? };

    Ok(res)
}

/// query_albums Run an RSQL filter over the user's albums. Fields: `title`, `artist`,
/// `year`, `cover`. Requires the `libraryRead` permission.
/// It takes input of types::LibraryQuery ()
#[allow(unused)]
pub(crate) fn query_albums(
    input: types::LibraryQuery,
) -> std::result::Result<Vec<types::LibraryAlbum>, extism_pdk::Error> {
    let res = unsafe { raw_imports::query_albums(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// query_artists Run an RSQL filter over the user's artists. Fields: `name`.
/// Requires the `libraryRead` permission.
/// It takes input of types::LibraryQuery ()
#[allow(unused)]
pub(crate) fn query_artists(
    input: types::LibraryQuery,
) -> std::result::Result<Vec<types::LibraryArtist>, extism_pdk::Error> {
    let res = unsafe { raw_imports::query_artists(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// query_library Run an RSQL filter over the user's tracks and get back the matches.
/// Requires the `libraryRead` permission; without it the call returns an
/// empty list. Example filter: `genre==rock;year>2000`.
/// It takes input of types::LibraryQuery ()
#[allow(unused)]
pub(crate) fn query_library(
    input: types::LibraryQuery,
) -> std::result::Result<Vec<types::Track>, extism_pdk::Error> {
    let res = unsafe { raw_imports::query_library(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// query_playlists Run an RSQL filter over the user's playlists. Fields: `name`,
/// `description`, `smart`, `created`. Requires the `libraryRead` permission.
/// It takes input of types::LibraryQuery ()
#[allow(unused)]
pub(crate) fn query_playlists(
    input: types::LibraryQuery,
) -> std::result::Result<Vec<types::LibraryPlaylist>, extism_pdk::Error> {
    let res = unsafe { raw_imports::query_playlists(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}
